### PR TITLE
Fix spelling error

### PR DESCRIPTION
**Pull request by valuta1995**
Changed insure to ensure

## What This PR Changes
- Spelling error in documentation

## What Needs To Be Reviewed
- N/A

## How To Give Feedback
Please leave your feedback as a [Github review](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).

### CODE REVIEW

**Comment by marqdevx** [comment]
Not sure about this change:
* Insure: https://dictionary.cambridge.org/dictionary/english/insure
* Ensure: https://dictionary.cambridge.org/dictionary/english/Ensure

@karlsoderby @valuta1995

**Comment by valuta1995** [comment]
Hi Marqdevx,

It appears US English is less strict and technically allows insure to be used as a synonym to ensure whereas UK English does not.

In UK English, insure is the act of offering insurance and being insured is that of having taken out an insurance whereas ensure means to make sure of something.

I retract my claim to a spelling error and would instead request the change to 'ensure' to ensure compatibility with both UK and US English ;)

**Review by marqdevx — APPROVED** [review]
@1n2 confirmed.
LGTM

**Comment by marqdevx** [comment]
Thanks for your contribution with this PR @valuta1995
😄

**Pull request merged**
