### PR TITLE
Edit button bug fix

### PR DESCRIPTION
**Pull request by jcarolinares**
## What This PR Changes
- Edit button bug fix

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Review by canchebagur — APPROVED** [review]
LGTM!

**Comment by jcarolinares** [comment]
preview even worse

now it's more broken, there are some tutorials that does not appear

**Comment by jhansson-ard** [comment]
@jcarolinares the links don't work, maybe you need to remove the "content" from the link? 

It now points here: 
image

**Comment by jcarolinares** [comment]
Bein an unsuccesful PR I'm closing it

**Pull request closed without merging**
