### PR TITLE
updated schematic [MKC-514]

### PR DESCRIPTION
**Pull request by jhansson-ard**
## What This PR Changes
Schematic was wrong according to the wire-diagram

This PR updates the schematic as well as a minor wire-move on the wire-diagram.
From this issue: https://github.com/arduino/docs-content/issues/306

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Review by marqdevx — APPROVED** [review]
LGTM

**Comment by marqdevx** [comment]
You did it, you can see it here https://github.com/arduino/docs-content/pull/310/commits/7ab7c0deec28b542e8f6f744aa99225342229dd4 😄

**Comment by marqdevx** [comment]
You mean the position right? f2708c5

**Review by Coding-Badly — CHANGES_REQUESTED** [review]
Please place the blue wire termination in the correct location.

image

**Comment by jhansson-ard** [comment]
@Coding-Badly I'm sorry, I didn't see your comment in time. I will fix this now ⭐

**Pull request merged**
