### PR TITLE
[PC-1688] Nano Matter: Technical Information Revamp

### PR DESCRIPTION
**Pull request by ArduinoBot**
## What This PR Changes
Nano Matter technical information revamp
- Schematics
- Pinout resources
- Tech specs
- Datasheet

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Review by mcmchris — APPROVED** [review]
LGTM

**Comment by jcarolinares** [comment]
Hello @jhansson-ard and @lukdog  I'm afraid we need you help guys regarding this special case

Validate Content Error is related with a not recommended underscore, maybe that should be a warning but in any of the cases due to the lack of admin permissions we need your help to merge this pull request

Launch was today so this is a priority for us, thank you

**Comment by jhansson-ard** [comment]
Hello! You need to move the datasheet folder to the "normal" folder tree, so [here in this folder](https://github.com/arduino/docs-content/tree/133fb3267dc79fcee2e02fb0d2a7714c13604131/content/hardware/03.nano/boards/nano-matter). This will not make any difference to the behavior we see now, but we should test it on oniudra just to be safe before we merge ⭐

**Review by martab1994 — APPROVED** [review]
LGTM thanks so much

**Pull request merged**
