### PR TITLE
updated link for OPTA

### PR DESCRIPTION
**Pull request by akash73**
## What This PR Changes
added https://docs.arduino.cc/hardware/opta

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Review by TaddyHC — DISMISSED** [review]
Thanks for the extension, lgtm! @jcarolinares , I think it would be nice if you could take a quick look at it too. It's regarding the added link to Opta documentation page instead of the store link (Which we haven't included since it could be shared with Finder) for the updated Arduino & Modbus article. I think it should be good but checking in just in case.

**Review by jcarolinares — DISMISSED** [review]
It's a nice solution for the store link problem, but, we have to wait, the link won't work and if possible I would move Opta to a new hardware block

**Comment by akash73** [comment]
@TaddyHC @jcarolinares not sure I've understood why is blocked. in the page there's no mention to any store link.
every product listed before the OPTA has a link do docs, not to the store.

**Comment by akash73** [comment]
up

**Review by jcarolinares — APPROVED** [review]
Unblocked

Looks good to me

Merging

**Pull request merged**
