### PR TITLE
DTB section updated

### PR DESCRIPTION
**Pull request by jcarolinares**
## What This PR Changes
- Updates regarding the DTB

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by jcarolinares** [comment]
cc @TaddyHC we are updating this section, @MaxPayne86 identified that the first method is not available anymore for a long time so I modified the section

cc @martab1994 thank you all for your collaboration to make this great!

**Comment by MaxPayne86** [comment]
@jcarolinares 

> a couple of methods
> In the case of the Portenta X8 with the Portenta Hat Carrier, the following official methods are supported

need to be amended too, the first because we have only one method now which is setting overlays u-boot variable. The second because this mechanism works always and is not tied to a particular carrier. More precisely the overlays are the hw configuration that the X8 is going to apply to itself, in order to support a certain hw

**Comment by TaddyHC** [comment]
@jcarolinares okay, thanks for the notice!

**Comment by jcarolinares** [comment]
@MaxPayne86 changed it to a more generic phrase that hopefully will work!

**Review by MaxPayne86 — APPROVED** [review]

**Pull request merged**
