### PR TITLE
PWM output using MATLAB Tutorial

### PR DESCRIPTION
**Pull request by MessiahJa**
This is a tutorial for another MATLAB based project similar to the one using Wi-Fi and Adruino NaNo.

## What This PR Changes
- (It also serves as an introduction of Arduino into MATLAB but requires less hardware, it is not to replace the original tutorial but to become something new. If it does not meet the requirements please notify me of how I may be able to standardize the tutorial. Thanks.)

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by jhansson-ard** [comment]
Hello @MessiahJa! It seems like, instead of making another PR with a new tutorial, you have changed an already made tutorial written by us. Was this your intention or did you want to add a new tutorial? :) 

If the latter, please look at our [Contribution page](https://github.com/arduino/docs-content/blob/main/CONTRIBUTING.md) with instructions. Thank you!

**Comment by marqdevx** [comment]
@Lenardgeorge @karlsoderby @aliphys 
Could you please take a look to this tutorial? Thanks.

If you agree to publish it, I fix the tutorial and merge it.

**Comment by aliphys** [comment]
@MessiahJa as I understand this PR is for a new tutorial. Since this is a Uno tutorial, can you make a new folder in `content/hardware/02.hero/boards/uno-rev3/tutorials` for your tutorial and place all assets there?
You can find more information on our contribution guidelines at: https://github.com/arduino/docs-content/blob/main/contribution-templates/README.md
Looking forward to have your contributions!

**Comment by MessiahJa** [comment]
Thank you all, @marqdevx @jhansson-ard  and @aliphys. I will fix all that I can based on your helpful comments and the template then pull in the correspoding folder.

**Comment by marqdevx** [comment]
Closing this PR as the fixes are on this one #222

**Pull request closed without merging**
