### PR TITLE
Kateryna lukina/certification updates

### PR DESCRIPTION
**Pull request by kateryna-lukina**
## What This PR Changes
- Docs certifications updates (removed old certificates/DoCs, added new ones)

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by karlsoderby** [comment]
Hey @kateryna-lukina, I see that you removed a lot of documents. Was this intentional? Just checking. It all looks good, but just to make sure any certifications are not removed by accident!

**Comment by kateryna-lukina** [comment]
Hey @karlsoderby  I have talked to Riccardo, he says we should keep both DoCs and Certificates on the website, so I have now fixed it and added them back. Should be all correct now

I have a question about Arduino Due certifications - we have the CE DoC and the UKCA DoC on GitHub but I do not see them on the Docs website, what could be the problem?

**Comment by kateryna-lukina** [comment]
Also I need to replace the REACH certificate with a new one, can you show me where it should be updated? I cannot find it

**Comment by karlsoderby** [comment]
@kateryna-lukina ah it was a very small typo that was behind that, I just fixed it here! So then all is good to go? Thanks for checking it out!

**Comment by kateryna-lukina** [comment]
Great, thanks! What about the REACH certification?

**Comment by karlsoderby** [comment]
@kateryna-lukina for some time now, all reach certificates are combined into one: https://docs.arduino.cc/resources/reach/arduino-reach.pdf

there is a specific section at docs.arduino.cc/certifications where you can access it :)

**Comment by kateryna-lukina** [comment]
Yeah I know, I mean where on GitHub is it? I have to update that document on Docs (it is unsigned there)

**Comment by karlsoderby** [comment]
@kateryna-lukina sorry my bad. It is stored [here](https://github.com/arduino/docs-content/tree/main/static/resources/reach), in the `static/resources/reach` folder.

**Comment by kateryna-lukina** [comment]
OK, updated now. No more changes from my side for now 😉

**Review by karlsoderby — APPROVED** [review]

**Pull request merged**
