### PR TITLE
Fix the circuit image in the Knock built-in example

### PR DESCRIPTION
**Pull request by chiepomme**
Hi! I'm a beginner in Arduino and was trying the Knock built-in example. Then I noticed that the circuit image differed from the schematic image, so I tried fixing it. I don't know what tool was used to create the circuit image, so I fixed it with Fritzing.

My apologies if I overlooked something.

## What This PR Changes
- Fix the circuit image in the Knock built-in example to match the schematic image.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by marqdevx** [comment]
Thanks for your PR!
Let me tag my colleague who has a better design view than me 😄 

Could you please check / update the drawing? @jhansson-ard

**Comment by jhansson-ard** [comment]
@chiepomme please check out this PR here if the new graphics are good enough! Thank you 🙏🏼 

https://github.com/arduino/docs-content/pull/344

**Comment by chiepomme** [comment]
@jhansson-ard Hi! I checked it! The new graphics are great, and the new explanation about the resistor and piezo is really useful especially for newbies like me. Thank you for accepting my suggestion and improving the doc!

Btw, thanks to the Knock tutorial, I was able to make an VR experience that a girl copies player's play. I really appreciate the tutorial!
https://twitter.com/chiepomme/status/1544272386953949184

**Comment by jhansson-ard** [comment]
That looks amazingly cool @chiepomme! Thank you for sharing! ⭐

**Pull request closed without merging**
