### PR TITLE
Update features.md

### PR DESCRIPTION
**Pull request by martab1994**
Fix typo

## What This PR Changes
- (Please explain here why you created the pull request and specify what it changes)

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Review by marqdevx — APPROVED** [review]
LGTM

**Comment by marqdevx** [comment]
I thin this is a duplicated PR, check #513 's changes 🤔 
If those are the same, please close one of both

**Comment by martab1994** [comment]
@marqdevx no it is not because one is for Portenta H7 Lite and the other one for Portenta H7 Lite Connected :)

**Comment by marqdevx** [comment]
You are right! my fault
On it 👌

**Pull request merged**
