### PR TITLE
Update web-editor with new key cloud-editor

### PR DESCRIPTION
**Pull request by Matteo-it**
Jira task: https://arduino.atlassian.net/jira/software/projects/WEDO/boards/381?selectedIssue=WEDO-5785

Merge after #1864

### CODE REVIEW

**Review by jacobhylen — APPROVED** [review]
Looks good from Maker side :)

**Comment by jcarolinares** [comment]
Hello

@Matteo-it you have to wait for pro approval, @jacobhylen keep in mind @Matteo-it just saw the approval

I've just realise randomly these changes, this is not acceptable

@Matteo-it and @jacobhylen please report me properly when something affects Pro Content, thanks

**Comment by Matteo-it** [comment]
Hello @jcarolinares,

I'm sorry, I was not clear that I had to wait for more than one approval, thank you for clarifying! 🙏🏻 
If changes to this PR are a problem I can make a revert 👍🏻

**Comment by jcarolinares** [comment]
Changes are great, no need to revert!

**Pull request merged**
