### PR TITLE
Benjamindannegard/pro docs restructure

### PR DESCRIPTION
**Pull request by BenjaminDannegard**
## What This PR Changes
- Changes the PRO section of the docs site

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by marqdevx** [comment]
Feedback? 👀  @BenjaminDannegard @sebromero @martab1994 @francescospissu @jcarolinares @karlsoderby 
image

**Review by martab1994 — APPROVED** [review]
Great thanks!

**Comment by marqdevx** [comment]
Should we move Education before the Portenta family? 🤔

**Comment by BenjaminDannegard** [comment]
> 

Something looks off on your screenshot. Looks like this on my machine
Screenshot 2022-10-12 151438

**Comment by marqdevx** [comment]
Yes, I deleted some stuff, yours is correct 👌

**Pull request merged**
