### PR TITLE
Portenta X8: Video Output [PC-891]

### PR DESCRIPTION
**Pull request by marqdevx**
## What This PR Changes
- Add Portenta X8 video output tutorial

### CODE REVIEW

**Comment by marqdevx** [comment]
Linter has a weird issue
image
With my offline built it was showing every picture fine.

**Comment by per1234** [comment]
Hi @marqdevx. I believe this remaining one:

```
❌ ERROR: Asset 'portentaX8-home-screen.PNG' is not used. Location: ../../content/hardware/04.pro/boards/portenta-x8/tutorials/display-output-webgl/content.md:1:1
❌ ERROR: Image doesn't exist: assets/portentaX8-home-screen.png Location: ../../content/hardware/04.pro/boards/portenta-x8/tutorials/display-output-webgl/content.md:137:19
```

Is caused by the file extension `.PNG`. On a case insensitive file system such as Windows, the path in the link:

```markdown
![X8 home-screen](assets/portentaX8-home-screen.png)
```

and the actual path of the file (`assets/portentaX8-home-screen.PNG`) are equivalent. But the linter runs on the case sensitive file system of Linux, where these are not the same.

My recommendation is to rename the image file to use the more standard `.png` extension.

**Review by BenjaminDannegard — APPROVED** [review]
LGTM

**Comment by marqdevx** [comment]
> Hi @marqdevx. I believe this remaining one:
> 
> ```
> ❌ ERROR: Asset 'portentaX8-home-screen.PNG' is not used. Location: ../../content/hardware/04.pro/boards/portenta-x8/tutorials/display-output-webgl/content.md:1:1
> ❌ ERROR: Image doesn't exist: assets/portentaX8-home-screen.png Location: ../../content/hardware/04.pro/boards/portenta-x8/tutorials/display-output-webgl/content.md:137:19
> ```
> 
> Is caused by the file extension `.PNG`. On a case insensitive file system such as Windows, the path in the link:
> 
> ```gfm
> X8 home-screen
> ```
> 
> and the actual path of the file (`assets/portentaX8-home-screen.PNG`) are equivalent. But the linter runs on the case sensitive file system of Linux, where these are not the same.
> 
> My recommendation is to rename the image file to use the more standard `.png` extension.

I did that but git didnt recognize the change (Should have used `git mv`) but yes Benjamin spotted and fixed by deleting and adding it again with the lower caps variant.

Thanks 😄

**Pull request merged**
