### PR TITLE
Add library specification to library tutorial

### PR DESCRIPTION
**Pull request by gvenzl**
This PR includes a reference to the library specification at the end of the article.

## What This PR Changes
- The library creation tutorial is great but lacks information on how to make the library available in the library manager. This PR adds a link to the library specification at the end of the tutorial.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by gvenzl** [comment]
Fixes #236

**Comment by per1234** [comment]
Thanks @gvenzl!

Although this does address some of the requests made in #236, it is missing [this part](https://github.com/arduino/docs-content/issues/236#issue-1235853111):

>with a library.properties example, and probably using the src/ subfolder

So I'm not sure it could be considered a complete resolution to #236.

CC: @matthijskooijman

**Comment by gvenzl** [comment]
Hi @per1234,

You are correct, it does not include that part.

I'm somewhat with @matthijskooijman, the tutorial probably should be overhauled in general, although note that the last revision date was the 23rd of May, just a couple of weeks ago.

Still, issue #236 open since 2016 and I just happened to run into the very same problem as well, spending half an hour trying to find the right information.
There seems to be no harm to at least adding this paragraph, for now, to help save other users some time, even if a bigger rewrite is coming in the future.

**Comment by per1234** [comment]
>There seems to be no harm to at least adding this paragraph, for now, to help save other users some time, even if a bigger rewrite is coming in the future.

I completely agree. I only made my previous reply to indicate that we should not necessarily consider https://github.com/arduino/docs-content/issues/236 100% resolved by this PR.

That doesn't mean this PR is required to provide a 100% resolution, only that we should not close https://github.com/arduino/docs-content/issues/236 if there are still unresolved components.

**Comment by gvenzl** [comment]
Gotcha! I've updated my previous comment to reflect that.

**Review by per1234 — APPROVED** [review]
Thanks @gvenzl!

**Pull request merged**
