### PR TITLE
Remove superfluous url_guide properties

### PR DESCRIPTION
**Pull request by sebromero**
## What This PR Changes
- This PR removes all the superfluous url_guide properties in the product files. These articles are used in the setup guide but are inferred by the specified core.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Review by karlsoderby — CHANGES_REQUESTED** [review]
Update: looks like there are several conflicts due to another PR that was merged earlier today (#726)

**Comment by jhansson-ard** [comment]
@sebromero any way we can fix the issues and merge this? 🙏🏼

**Comment by sebromero** [comment]
@jhansson-ard @karlsoderby Please check and merge

**Comment by jhansson-ard** [comment]
This PR is not relevant anymore because of the changes to Docs.

**Pull request closed without merging**
