### PR TITLE
Added to new boards. Metadata updated. Hardware updated

### PR DESCRIPTION
**Pull request by jcarolinares**
## What This PR Changes
- Updates to add the tutorial to new boards

## Contribution Guidelines
- [x ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by jcarolinares** [comment]
@marqdevx or @martab1994 please approve this PR

The tutorial will be present on:

Portenta Vision Shield
Portenta H7
Portenta H7 Lite
Portenta H7 Lite Connected
Nano BLE Sense
Nano BLE Sense Rev.2
Nano RP2040

**Comment by jcarolinares** [comment]
Solving a metada problem please wait

**Comment by jcarolinares** [comment]
Content creator responsible -> Looks good to merge

**Review by martab1994 — APPROVED** [review]
Amazing thanks!

**Pull request merged**
