### PR TITLE
Updated shift out diagram [MKC-548]

### PR DESCRIPTION
**Pull request by jhansson-ard**
## What This PR Changes
- The diagrams in the ShiftOut example was showing errors. See issue here: https://github.com/arduino/docs-content/issues/384

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

### CODE REVIEW

**Comment by karlsoderby** [comment]
@jhansson-ard I think you need to rebase this cause of the gatsby issue we had last week :)

**Comment by jhansson-ard** [comment]
@karlsoderby please review 🙏🏼

**Comment by sebromero** [comment]
@per1234 Can we merge this?

**Comment by jhansson-ard** [comment]
closing this PR since it has not moved forward.

**Pull request closed without merging**
