### PR TITLE
Add quick fix for italic styling

### PR DESCRIPTION
**Pull request by sebromero**
Arduino's design system doesn't provide italic styling to emphasise text. As a result we should use bold emphasis only.

## What Needs To Be Reviewed
- Check if the "Fix linter issues" correctly replaces occurrences of italic styling.

## How To Give Feedback
Please leave your feedback as a [Github review](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews). 
You can add comments to specific lines of content / code and ideally use Github's [suggestion feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request). 🙏

### CODE REVIEW

**Comment by jhansson-ard** [comment]
It seems like it missed one here, what do you think is the issue?
image

Here was also another weird example, where it seems something has gone wrong:
image

**Comment by sebromero** [comment]
@jhansson-ard Good catch! I'll have a look

**Comment by sebromero** [comment]
@jhansson-ard should be fixed now

**Comment by sebromero** [comment]
@jhansson-ard actually no, it introduced a new problem 😓

**Comment by sebromero** [comment]
@jhansson-ard Okay, now I'm more confident. Should work :-D

**Comment by jhansson-ard** [comment]
Now it seems as it takes even the image links 😬 
image

**Comment by sebromero** [comment]
@jhansson-ard Please try again 🙏

**Review by jhansson-ard — APPROVED** [review]

**Pull request merged**
